openzipkin/docker-zipkin

collector/Dockerfile
collector/collector-cassandra.scala

I provided a new collector-cassandra.scala config file that sets the log level to INFO.
By default the log level was set to DEBUG which means that every span submitted to the collector was being logged.  This slows down the collector and generates a huge log.
I guess INFO is good enough. You get some feedback when the collector is started but you don't get lots of irrelevant log entries. Changing it to another log level is also straightforward. The level is defined in collector-cassandra.scala

Log level change for zipkin-collector

---

deploy/build.sh
deploy/deploy.sh

This is generally good practice, and specifically stops the build process when one image fails to build. Especially useful when the build of the base image fails for some reason; without this change, it's ignored and the rest of the images are built from the last successfully built base image. This leads to much weeping and gnashing of teeth.

Apply the "unofficial bash strict mode" to deploy/build.sh

---

deploy/deploy.sh

According to [docker-run](https://docs.docker.com/reference/run/#expose-incoming-ports) command reference, format of `-p` option is `hostPort:containerPort`.
But current `deploy.sh` assumes `containerPort:hostPort` and failed to change host port by `PUBLIC_PORT` value.
This PR fixes it.

Fix docker run -p option format of deploy

---

LICENSE

To use the same license as used in https://github.com/openzipkin/zipkin/
The big question is of course not the diff in here, but whether we can just go ahead and do this, what kind of permission we need to get, and how to document it properly. Looking for help here, no idea where to even start.

Relicense under Apache 2.0

---

README.md
RELEASE.md
cassandra/Dockerfile
collector/Dockerfile
query/Dockerfile
release.sh
web/Dockerfile

This is a better implementation of https://github.com/openzipkin/docker-zipkin/pull/38, see the description of that PR for a detailed discussion of the trade-offs behind this.
When this is merged, the release script will still be failing at the "sync to Docker Hub" step, since at this moment the repos on Docker Hub are automated builds, which don't accept direct pushes. We'll need to migrate those to normal repositories.
After that, the next step is running this process on Travis, triggered by a tag (say `release-1.4.0`, to not confuse the build triggers in Quay.io)

Automated release process using Quay.io

---

docs/user-guide.md

- Docker Toolbox's installer doesn't make any mention of the hello world
image, invites the user to try to run the Docker Quickstart Terminal
app instead.
- Point to the schema definitions directly.

Update the user guide

---

docker-compose-mysql.yml
mysql/Dockerfile
mysql/install.sh
mysql/run.sh
release.sh

This adds a MySQL image so that we can test our corresponding spanstore.
This adds on our base image to keep size down, and also help capture
the minimum configuration needed when creating the zipkin MySQL schema.
By having a small image, our travis builds take longer, those looking
for a 5 minute quick start are more likely to be able to achieve that,
and those troubleshooting docker problems will spend less time pulling
images.

Adds MySQL image for testing

---

base/.cassandra_profile
base/.mysql_profile
base/Dockerfile
collector/run.sh
docker-compose-mysql.yml
docker-compose.yml
query/run.sh
web/run.sh

Users can now assign `STORAGE_TYPE` as `cassandra` or `mysql` to start
zipkin on the corresponding backend.
Fixes #56

Uses STORAGE_TYPE variable to decouple span storage implementations

---

base/Dockerfile

As an implementation of https://github.com/openzipkin/docker-zipkin/issues/62
Comparing `delitescere/jdk` and `openzipkin/jre-full`: https://imagelayers.io/?images=delitescere%2Fjdk:1.8.0_60,openzipkin%2Fjre-full:1.8.0_60

Use openzipkin/jre-full as the base Docker image

---

base/.kafka_profile
base/.scribe_profile
base/Dockerfile
collector/run.sh
docker-compose-mysql.yml
docker-compose.yml
kafka/Dockerfile
kafka/install.sh
query/run.sh
release.sh
web/run.sh

This adds an image for Kafka/Zookeeper, which can be used to test kafka
integration of zipkin with instrumentation including Ruby, Finagle, Brave &
HTrace. This exports a new variable to designate the `TRANSPORT_TYPE`,
with choices of `scribe` and `kafka`.
At the moment, there's no Finagle Kafka integraion. I tested this with
an experimental Brave span transport, used in the `zipkin-java` project.
The image bundles together Kafka and Zookeeper using Runit as the entry-
point. This is for simplicitly and to keep the requirements as small as
possible to run tests (ex. we are already several containers). The
approach used is similar to baseimage-docker.
See https://github.com/openzipkin/brave/issues/102
See https://github.com/apache/incubator-htrace/commit/9ebdafb45df03a4b0d90c77af65e0bd21c09 …

Adds Kafka image and TRANSPORT_TYPE to select it with

---

base/.http_profile
base/Dockerfile
docker-compose-mysql.yml
docker-compose.yml

Before, zipkin required a collector process for the purpose of self-
tracing. Collector is still supported, particularly to serve legacy
instrumentation. However, it is no longer required as zipkin can
self-trace over http.
This change updates the MySQL example (docker-compose-mysql.yml),
showing how self-tracing can work without a collector process.

Migrates zipkin self-tracing off scribe and minifies MySQL example

---

base/Dockerfile

This was added before we got our cassandra story working.

Removes orphaned install of netcat-openbsd

---

README.md
base/Dockerfile
collector/run.sh
query/run.sh
web/run.sh

Customizations including heap size or trust stores require modifying JRE
arguments. This adds `JAVA_OPTS`, which can be used to do that.
This is in the base image, so could be used by anything that derives
from it, including zipkin-web, zipkin-query and zipkin-collector.
Ex.
```yaml
environment:
- JAVA_OPTS=-Xmx1G
```
See https://github.com/openzipkin/zipkin/issues/885

Allows customization of JRE via JAVA_OPTS

---

README.md
base/.cassandra_profile
docker-compose-mysql.yml
docker-compose.yml
web/run.sh

The docker-compose-mysql.yml file appears to be incomplete, as it is not
running the collector container. This branch switches that configuration
to be an extention of the default docker-compose.yml file, using
docker-compose overrides, described here:
https://docs.docker.com/compose/extends/#multiple-compose-files
In addition, I've fixed an issue where the zipkin-cassandra container
would not exit if the storage type was not configured correctly. And
I've modified the zipkin-web container to allow overriding the query
service address without requiring linking.

Use overrides for docker-compose mysql setup

---

README.md
docker-compose-legacy.yml
docker-compose-mysql.yml
docker-compose.yml

Convert the docker-compose.yml and docker-compose-mysql.yml files to use
the version 2 docker-compose file format, as described here:
https://docs.docker.com/compose/compose-file/#version-2
The v1 configuration is still available in the docker-compose-legacy.yml
file, and I've re-added the collector container to that configuration,
since it is now denoted to be legacy.

Switch to docker-compose v2 configs

---

README.md

This branch updates the README with info about docker-specific environment variables that can be set to control a running docker container. I've also included links back to the Zipkin documentation of other available environment variables where appropriate. And I've added information about the minimum versions of docker / docker-compose required to run the v2 docker-compose files. I'm not super familiar with how all of the containers are configured, so please correct if I've made any mistakes.

Add runtime configuration section to readme

---

README.md
docker-compose-elasticsearch.yml
elasticsearch/Dockerfile
release.sh
zipkin/zipkin/.elasticsearch_profile

This adds a test image for Elasticsearch, similar to how we have for
Cassandra and MySQL. This completes parity, as we now have a test image
for all supported storage types.

Adds a basic Elasticsearch image

---

README.md
docker-compose-elasticsearch.yml
docker-compose-mysql.yml
docker-compose.yml

This adds another service which runs the [dependencies job](https://github.com/openzipkin/docker-zipkin-dependencies) via cron.
Fixes #75
Fixes #76

Adds dependencies cron job to docker-compose files

---

README.md
docker-compose.yml
docs/user-guide.md

It has been a while since zipkin-web. It is better for us to use the
canonical port for zipkin vs something it doesn't naturally advertise.
Fixes #103

Stops advertising port 8080 as it easily clashes with other processes

---

README.md
docker-compose-kafka.yml
docker-compose-ui.yml
release.sh
zipkin-ui/Dockerfile
zipkin-ui/nginx.conf

This container doubles as a skeleton for creating proxy configuration around
Zipkin like authentication, dealing with CORS with zipkin-js apps, or
terminating SSL.
It can also be adapted to test new UIs, such as https://github.com/openzipkin/zipkin-ui
Related issues which having an example NGINX config could help with:
See https://github.com/openzipkin/zipkin/issues/782
See https://github.com/openzipkin/zipkin/issues/1135
See https://github.com/openzipkin/zipkin/issues/1171
See https://github.com/openzipkin/zipkin/issues/974

Adds zipkin-ui image using NGINX

---

README.md
docker-compose-elasticsearch.yml
elasticsearch5/Dockerfile
elasticsearch5/config/elasticsearch.yml
release.sh
zipkin/zipkin/.elasticsearch_profile

This changes the default Elasticsearch transport to http so that we can
use Elasticsearch 5 as the test image, as well see self-traces.
The test image of Elasticsearch is version 5.x which is [more strict](https://github.com/docker-library/docs/tree/master/elasticsearch#host-setup) about virtual memory. You will need to adjust accordingly (especially if you
notice elasticsearch crash!)
```bash
$ sudo sysctl -w vm.max_map_count=262144
$ docker-machine ssh default "sudo sysctl -w vm.max_map_count=262144"
```

Use Elasticsearch 5 in test image, switching default transport to http

---

README.md
docker-compose-ui.yml
zipkin-ui/Dockerfile
zipkin-ui/nginx.conf
zipkin-ui/run.sh

This changes the zipkin-ui image to rewrite nginx configuration on start
based on the `ZIPKIN_BASE_URL` variable, which defaults to
'http://zipkin:9411'. Users can change this variable to point at a
different zipkin host such as a kubernetes pod.
See https://github.com/openzipkin/zipkin-ui/pull/38
Fixes #134

Allow configuring ZIPKIN_BASE_URL for zipkin-ui image

---

README.md

Updated documentation to use the kafka10 docker-compose configuration as the primary example for testing with Kafka. Also added example of switching to docker-compose-kafka.yml in order to use the kafka 0.8 collector.

Updated docs with how to run the kafka10 collector

---

docker-compose.yml

It seems that Scribe is disabled by default:
```yml
...
```
But a line in docker-compose.yml states that it was enabled by default. I just corrected it to state that Scribe was disabled by default

Correct the fact that Scribe is disabled by default

---

README.md
docker-compose.yml
prometheus/create-datasource-and-dashboard.sh
prometheus/prometheus.yml

Add Prometheus, Grafana to `docker-compose.yml`. Document basic usage and setup. See #121 for reasoning.
I attempted to "ship" with a state where Grafana is already configured, but it's not completely trivial (where do you store the initial state? How do you get it to Grafana) leading to complexity. It would also remove some of the learning we expect to provide - automating it here means users will need to re-discover it later.

Fix #121: Add example prometheus setup

---

cassandra/Dockerfile
cassandra/run.sh
elasticsearch/Dockerfile
elasticsearch5/Dockerfile
elasticsearch6/Dockerfile
zipkin-ui/Dockerfile
zipkin-ui/run.sh
zipkin/Dockerfile

Allow Zipkin to quickly stop in docker-compose by propagating signals to Java.
The signal was sent to bash and ignored.

Propagate SIGTERM to Java in Dockerfiles

---

zipkin/Dockerfile

To (minimally) reduce the image size, it's just a small addition, thought it might be ok to add.

Add --no-cache option to zipkin dockerfile

---

elasticsearch6/Dockerfile
elasticsearch6/config/elasticsearch.yml

@michael1589 reported our test elasticsearch6 image was broken. This happened due to 2 known issues
Adding workarounds from the following:
https://github.com/elastic/elasticsearch/pull/31003
https://discuss.elastic.co/t/elasticsearch-failing-to-start-due-to-x-pack/85125/6

Fixes crash in elasticsearch6 image for various reasons

---

README.md
docker-compose-kafka.yml
kafka/Dockerfile
kafka/install.sh

This follows advice from @jeqo and makes Kafka listen on another port
for non-docker apps. For example, if running a demo not in docker, you
can set its broker list to localhost:19092
Closes #186

Upgrades Kafka to 2.0 and listens on localhost:19092

---

elasticsearch6/Dockerfile

This seems to be the proper path of the ml module to be removed. The original one throws exception:
```
[2018-11-27T14:03:04,025][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: org.elasticsearch.bootstrap.BootstrapException: java.io.IOException: Cannot run program "/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller": error=2, No such file or directory
at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.4.2.jar:6.4.2]
at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.4.2.jar:6.4.2]
at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) …
```

fix(elasticsearch6): remove ml module

---

zipkin/Dockerfile
zipkin/zipkin/run.sh

When we switched to JRE 11, we also switched to distroless. There is a
regression where if you set JAVA_OPTS, it undoes any profile setup for
3rd party modules like zipkin-aws. This could be perceived as messages
from SQS not being processed because sqs wasn't loaded.
Instead, this creates a separate env MODULE_OPTS to hold the layered
config. I tested this on zipkin-aws.

Adds MODULE_OPTS to avoid clobbering 3rd party profile config

---

zipkin/Dockerfile

While zipkin has no scripts that directly reference `/bin/sh`, some users with their own `Dockerfile` might want to add them. While we could put the onus of symlinking these to the users as they should be using a `Dockerfile` for their customization, it's small enough that it seems reasonable to do it in our image.
Fixes #206

Symlink busybox into bin.

---

README.md
cassandra/Dockerfile
elasticsearch/Dockerfile
elasticsearch5/Dockerfile
elasticsearch6/Dockerfile
elasticsearch7/Dockerfile
kafka/Dockerfile
zipkin/Dockerfile

this reduces confusion. For example, the zipkin-aws missed reading profile config due to the mildy unintuitive difference between /home/zipkin and /zipkin where everything is.

sets homedir for each non-root user

---

docker-compose-elasticsearch-aws.yml

Note: a small instance will fall over after about 30 seconds of load :)
Though a small instance seems to stay alive against brave-webmvc-example
```
wrk -t4 -c64 -d20s http://localhost:8081 --latency
```
When ES fails it doesn't fail nicely. Often results in the following
errors instead of an http response:
These warnings will fill logs at the rate of traffic, so I've asked
Armeria what we should do about it.
```
zipkin                      | 2019-08-17 10:35:32.840  WARN 1 --- [orker-epoll-2-4] c.l.a.c.HttpResponseDecoder              : Unexpected exception:
zipkin                      |
zipkin                      | com.linecorp.armeria.client.ResponseTimeoutException: null
```
Also, there seems to be a glitch somewhere, as when I turn on throttling
in attempts to mitigate the above, it …

Adds AWS Elasticsearch Service image so that it is easier to troubleshoot

---

zipkin/zipkin/run.sh

After researching before and after startup times with Spring Boot 2.1
vs 2.2, the largest win for startup time, regardless of version, is to
not use `PropertiesLauncher`.
Here is basic startup time before and after with the 2.17.2 version of
Zipkin:
Before (using PropertiesLauncher)
```bash
Started ZipkinServer in 3.641 seconds (JVM running for 5.009)
```
After (running the main class)
```bash
Started ZipkinServer in 3.267 seconds (JVM running for 4.31)
```
Note: even before this change we extracted Zipkin's jar first, so the
entire gains here are only from not using `PropertiesLauncher`.

Switches to launch with main class vs PropertiesLauncher when possible
