README.md, base/Dockerfile, cassandra/install.sh
=> Updates to use openzipkin as the authoritative repo

base/Dockerfile
Don't checkout the gradle branch
=> Gradle is now master

base/Dockerfile, cassandra/install.sh, collector/collector-cassandra.scala, collector/run.sh, query/run.sh
squashes and tidies #20
Closes #20
=> Fixes drift due to update to zipkin 1.2.1

collector/Dockerfile, query/Dockerfile, web/Dockerfile
As seen in https://hub.docker.com/r/openzipkin/zipkin-base/tags/
=> Use new shiny openzipkin base image

RELEASE.md, docker-compose.yml
This closes the story-arc "Release the <del>Krakken</del><ins>Cassandra</ins>", and opens the way for the next episode "Attack of the Minimal Base Images"
=> Version zipkin-cassandra the same as the other images

docker-compose.yml
=> Expose Cassandra's default port to the host

release.sh
I'd like to go on record saying I really strongly dislike that the same command has different arguments on BSD and GNU.
=> Fail early if jq or GNU date is not installed

release.sh
The "latest" tag is the default tag in Docker, whenever someone pulls `openzipkin/zipkin-cassandra`, they are pulling `latest`. Before this change we didn't create this tag.
The refactor of `sync-quay-tags` changes its arguments from
subminor_tag minor_tag major_tag images...
to
reference_tag "tags to move" images...
to accomodate syncing just the `latest` tag on `zipkin-base` to Docker Hub.
=> Let's create the "latest" tag :)

docs/user-guide.md
=> add user-guide.md

docker-compose.yml, query/run.sh, web/run.sh
=> Enables tracing of zipkin-web and zipkin-query

collector/run.sh, docker-compose.yml, query/run.sh
=> Removes cassandra block-loop as network connections are now lazy

release.sh
Pushing to dockerhub occasionally fails due to various intermittent problems (see https://travis-ci.org/openzipkin/docker-zipkin/builds/87597647 for an example). This change automates the retry we used to do manually.
=> release.sh: Retry docker push to dockerhub

base/.redis_profile, base/Dockerfile
=> Added redis profile to base image

collector/Dockerfile, collector/run.sh, query/Dockerfile, query/run.sh, web/Dockerfile, web/run.sh
=> Graceful shutdown handling of containers

README.md, docker-compose-kafka.yml, kafka/Dockerfile, kafka/install.sh
Tested with brave-resteasy-example with Docker Toolbox on OS/X
Fixes #85
=> Adds KAFKA_ADVERTISED_HOST_NAME and example kafka file

kafka/install.sh
Looks like 'runit' was moved from testing repo to community
=> fixing alpine repository for runit

zipkin/zipkin/.elasticsearch_profile
Changes the test to allow ES_AWS_DOMAIN in addition to ES_HOSTS.
=> Allow passing ES_AWS_DOMAIN via docker

mysql/Dockerfile, mysql/configure.sh, mysql/install.sh
Introduce 'install' and 'configure' steps. 
Closes #126
=> Split MySQL image

README.md, RELEASE.md, zipkin-ui/Dockerfile
This allows users to easily try the new UI, which can help it mature.
See https://github.com/openzipkin/zipkin-ui/issues/10
=> Switches default zipkin-ui image to use the experimental new UI

README.md, elasticsearch6/Dockerfile, elasticsearch6/config/elasticsearch.yml
see https://github.com/openzipkin/zipkin/issues/1676
=> Adds elasticsearch6 for testcontainers tests

README.md, RELEASE.md, zipkin-ui/Dockerfile, zipkin-ui/nginx.conf
The experimental UI is not maintained
reverts cd49996910ec5e538952b9725cb261ec5d68aaf3
Fixes #160
=> Reverts nginx example to the standard UI

README.md, docker-compose.yml
=> Adds logging example to README

cassandra/install.sh, cassandra/run.sh
Should fix https://github.com/openzipkin/docker-zipkin/issues/164
=> Volume mount workaround

cassandra/install.sh, docker-compose-cassandra.yml
This was cause by drift in the last version
See https://github.com/openzipkin/zipkin/pull/1876
=> Adds missing index install setup step

README.md, docker-compose-kafka.yml, docker-compose-kafka08.yml
See https://github.com/openzipkin/zipkin/issues/2080
=> Makes Kafka 0.10+ the default setup

cassandra/Dockerfile, cassandra/README.md
@adriancole not sure if it's ok with a branch here or if you'd rather a branch in a fork.
anyway, here's what i believe is the required bump to 3.11.3
=> bump to use Cassandra-3.11.3

zipkin-ui/README.md
=> Explains the zipkin UI proxy setup so others might know why it exists

zipkin-ui/Dockerfile
This makes it easier for people to try the UI
cc @making @drolando @openzipkin/ui
=> Makes Lens the default UI for the zipkin-ui container

elasticsearch5/Dockerfile, elasticsearch7/Dockerfile, elasticsearch7/config/elasticsearch.yml, elasticsearch7/config/log4j2.properties, release.sh
see https://github.com/openzipkin/zipkin/pull/2398
=> Adds Elasticsearch 7 test image

README.md, cassandra/Dockerfile, cassandra/install.sh, docker-compose-mem.yml, docker-compose.yml, elasticsearch/Dockerfile, elasticsearch5/Dockerfile, elasticsearch6/Dockerfile, elasticsearch7/Dockerfile, kafka/Dockerfile, mysql/Dockerfile, mysql/configure.sh, zipkin-ui/Dockerfile, zipkin-ui/README.md, zipkin/Dockerfile
See https://github.com/apache/incubator-zipkin/issues/2629
=> Reverts back to OpenZipkin dependencies

README.md, RELEASE.md, docker-compose-slim.yml, release.sh, zipkin-slim/Dockerfile, zipkin-slim/zipkin/.elasticsearch_profile, zipkin-slim/zipkin/run.sh
This will be merged and released so that the infrastructure is present and working. We can do re-cuts of this image based on feedback after merge.
=> Adds zipkin-slim image

zipkin-slim/zipkin/run.sh, zipkin/zipkin/run.sh
=> Uses full path when building classpath
